### PR TITLE
Bump nyc to 13.x

### PR DESCRIPTION
**Pull request by LinusU**
It's about to be promoted to stable 🙌  istanbuljs/nyc#902

### CODE REVIEW

**Comment by LinusU** [comment]
Ah right, Node 4.x support is dropped.

Hmm, I think we should drop that as well and release a new major (0.7.0) since Node.js 4.x is EOL.

**Comment by coreyfarrell** [comment]
This module is has `"instrument": false` so this is not actually running the updated instrumenter included by nyc@13, it's using the old version included by babel-plugin-istanbul@4.  Updating the babel plugin takes more effort as it is a babel 7 plugin.

**Comment by LinusU** [comment]
@mnkhouri added that here: 3f94e0b 🙌

**Comment by mnkhouri** [comment]
@LinusU LGTM!

Ok to wait on merging this until after https://github.com/depcheck/depcheck/issues/265 , since it is a breaking change?

**Comment by LinusU** [comment]
yeah, sounds good!

**Comment by nkbt** [comment]
I think it lacks package-lock changes...

**Comment by LinusU** [comment]
Rebased on master

**Pull request merged**
