### PR TITLE
Mark the peer dependencies as dev dependencies too.

### PR DESCRIPTION
**Pull request by lijunle**
/cc @LinusU

### CODE REVIEW

**Comment by LinusU** [comment]
Isn't the accepted practice that you include your dependencies peer-dependencies as your own dependencies? That is, just adding them as dependencies...

Also, I had a warning about `eslint-plugin-react` being an unmet peer dependency as well. Maybe that should go on the list also...

**Comment by lijunle** [comment]
We do not use `eslint-plugin-react` in our code. That one is fine to let it leave.

Not everybody use typescript and SASS parser, to whom use them, they will install typescript and SASS parser at project level. That is exactly how peer dependency works.

I have ideas to resolve these failing tests. The idea is to mark them as dev dependencies and peer dependencies.

**Comment by LinusU** [comment]
Ignore my stupid comment, I thought that it was peer dependencies to one of our dependencies :laughing:

**Comment by lijunle** [comment]
Actually, they are. We depends on their parse function to parse `.ts` (Typescirpt) files, `.sass` and `.scss` (SASS) files. However, I don't want to install everything then the user only use plain JavaScript.

**Pull request merged**
