### PR TITLE
Allow additional ESLint config file names.

### PR DESCRIPTION
**Pull request by goloroden**
According to [ESLint documentation](http://eslint.org/docs/user-guide/configuring#configuration-file-formats), a config file may have an extension. Hence I replaced the hard-coded comparison by a regular expression that matches all possible file names.

### CODE REVIEW

**Comment by goloroden** [comment]
I have seen that two of the three build steps failed, but IMHO this is fine, because:

- `codecov/project` is yellow for the other PRs, too. Apparently there is something not working.
- TravisCI successfully ran the tests, but failed when trying to talk to a coverage url. So the part that is really important passed.
- AppVeyor is green :-)

**Comment by lijunle** [comment]
@goloroden Thanks very much for contributing this project. The code looks good to me. Just one more point, could you please modify test code to cover the support? I suppose to add a for-loop in around [this line](https://github.com/depcheck/depcheck/blob/master/test/special/eslint.js#L102).

BTW, I will handle this test-coverage is failing. Don't worry about that. 😺

**Comment by goloroden** [comment]
Thanks for your fast response :-)

I have added to the tests what was needed to test the possible options.
Looking forward to the merge :-)

**Comment by lijunle** [comment]
Merged! Thank you for helping this!

**Comment by lijunle** [comment]
@goloroden Do you want a new version on this?

**Comment by goloroden** [comment]
Basically I'd say yes, but maybe let's wait until the next PR regarding issue #174 is also merged (I need both of them for a project I'm currently working on). Is that okay for you?

**Comment by lijunle** [comment]
Sure! 👍

**Pull request merged**
