### PR TITLE
fix: fixing broken gatsby parser

### PR DESCRIPTION
**Pull request by chris-hammond**
This PR fixes Gatsby config parsing by updating the names of some internal object fields and adding support for TemplateLiterals which are used in several examples.

### CODE REVIEW

**Comment by rumpl** [comment]
Cool! Could you add a test for this?

**Comment by chris-hammond** [comment]
@rumpl I think that test case should cover it!

**Review by rumpl — APPROVED** [review]

**Comment by rumpl** [comment]
Awesome, thank you @chris-hammond 

I'll whip up a new version tomorrow with this fix

**Comment by chris-hammond** [comment]
Thanks @rumpl ! Any update on releasing the new version?

**Pull request merged**
