### PR TITLE
Support node: prefix for builtin modules

### PR DESCRIPTION
**Pull request by karlhorky**
Hi there, thanks for `depcheck`, really great!

Just a quick PR to also support the builtin module specifiers with the new `node:` prefix introduced in Node v16 (will be backported to v14 soon)

Ref: https://twitter.com/jasnell/status/1385238402149150721

### CODE REVIEW

**Comment by kevinoid** [comment]
I'd also like to see `node:` supported.  Thanks for working on it @karlhorky!

Also wanted to add a quick note that you may want to consider using [`is-core-module`](https://github.com/inspect-js/is-core-module) (which was split from [`resolve`](https://github.com/browserify/resolve) in browserify/resolve@7c26483) so that you don't have to maintain your own list of core modules.

**Comment by kevinoid** [comment]
> `node:` prefix introduced in Node v16 (will be backported to v14 soon)

Also, a quick note that [`node:` support was backported to v14.13.1 and v12.20.0](https://nodejs.org/api/esm.html#esm_node_imports).

**Comment by karlhorky** [comment]
@kevinoid Wow, really cool, thanks for the heads up!

I've commented about this also over at DefinitelyTyped on the PR to `@types/node` where they reverted the `node:` prefix feature:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52595#issuecomment-850967327

**Comment by karlhorky** [comment]
> Also wanted to add a quick note that you may want to consider using [`is-core-module`](https://github.com/inspect-js/is-core-module) (which was split from [`resolve`](https://github.com/browserify/resolve) in [browserify/resolve@7c26483](https://github.com/browserify/resolve/commit/7c26483)) so that you don't have to maintain your own list of core modules.

Yeah @rumpl, I agree here - if you would prefer that I switched it out for this other well-maintained module instead, happy to give that a shot.

**Comment by karlhorky** [comment]
Ah, maybe `require` / CommonJS support is not quite there yet for v14 and v12:

> In Node 16 `require('node:fs')` works, but it looks like it still doesn't in 14.17.0.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52595#issuecomment-851015583

**Comment by kevinoid** [comment]
Good catch @karlhorky, I had missed that!

Looks like `require()` support is being held for a bit before backporting: https://github.com/nodejs/node/pull/37246#issuecomment-827666641

**Comment by rumpl** [comment]
> > Also wanted to add a quick note that you may want to consider using [`is-core-module`](https://github.com/inspect-js/is-core-module) (which was split from [`resolve`](https://github.com/browserify/resolve) in [browserify/resolve@7c26483](https://github.com/browserify/resolve/commit/7c26483)) so that you don't have to maintain your own list of core modules.
> 
> Yeah @rumpl, I agree here - if you would prefer that I switched it out for this other well-maintained module instead, happy to give that a shot.

@karlhorky that would be awesome, we used to use punycode but had to [remove it](https://github.com/depcheck/depcheck/issues/628), I'll be happy to merge a PR that would use `is-core-module` :)

**Comment by karlhorky** [comment]
@rumpl ok done in [`91ec86f`](https://github.com/depcheck/depcheck/pull/635/commits/91ec86f2080e6303f3bd8f5bd22d78b2e25accd8)

**Comment by rumpl** [comment]
Thanks! Could you squash your two commits and then we can merge?

**Comment by karlhorky** [comment]
Hm, I did something wrong here with the interactive rebase - one second.

**Comment by karlhorky** [comment]
Ok, looks better now, seems good from my side.

**Comment by karlhorky** [comment]
Oops, forgot one of the imports, removed it.

**Review by rumpl — APPROVED** [review]

**Comment by rumpl** [comment]
Thanks!

**Comment by karlhorky** [comment]
Glad to help, thanks for the merge! Will this be published in a new minor version (`1.5.0`)?

**Comment by rumpl** [comment]
It will yes, I'll push a new version later in the day (after I finish my real job 😅)

**Comment by karlhorky** [comment]
No rush, big thanks for all of your work on this project!

**Comment by karlhorky** [comment]
@rumpl any news on a new version?

**Comment by rumpl** [comment]
I just push the 1.4.2 tag, it should be available on npm soon, sorry about that 

Screenshot 2021-06-25 at 14 27 42

**Comment by rumpl** [comment]
Oh no... travis actually doesn't work any more 😭

**Comment by rumpl** [comment]
🎉 https://www.npmjs.com/package/depcheck/v/1.4.2

**Comment by karlhorky** [comment]
Thanks! hehe meme game on point

**Pull request merged**
