### PR TITLE
Include the names of each special in the README

### PR DESCRIPTION
**Pull request by rouanw**
to make it easier to find which options to pass to `depcheck`.

I couldn't find the Grunt special in the codebase - does it still exist?

### CODE REVIEW

**Comment by rouanw** [comment]
The build failure appears unlinked to my changes to the `README`:

```sh
AssertionError: [ 'cross-env' ] deepEqual []
    at /home/travis/build/depcheck/depcheck/build/check-json.js:27:12
    at check (/home/travis/build/depcheck/depcheck/build/check-json.js:25:10)
    at _callee$ (/home/travis/build/depcheck/depcheck/build/check-json.js:46:3)
    at tryCatch (/home/travis/build/depcheck/depcheck/node_modules/regenerator-
# ...
The command "npm run depcheck-json" exited with 1.
```

**Comment by rouanw** [comment]
@lijunle will you please take a look? 🔦

**Comment by haggholm** [comment]
Ditto, blocking https://github.com/depcheck/depcheck/pull/205.

It seems that depcheck is in fact failing to detect all of its own dependencies(!); the `test-coverage` npm script uses `node_modules/.bin/cross-env`, but (I suppose) because `cross-env` is never required by any JS code, it isn’t recognised as a dependency—hence, depcheck fails its own check.

This can be fairly easily worked around by changing
```js
  "scripts": {
    // ...
    "depcheck": "node ./bin/depcheck",
    // ...
  },
```
to
```js
  "scripts": {
    // ...
    "depcheck": "node ./bin/depcheck --ignores=cross-env",
    // ...
  },
```
but it feels a bit dirty to have a workaround for depcheck *in depcheck itself*...

**Comment by rouanw** [comment]
Thanks @lijunle 😄

**Pull request merged**
