### PR TITLE
Support for JSON configuration in package.json

### PR DESCRIPTION
**Pull request by znarf**
I want to be able to add a global configuration in projects adding a `depcheck` section in `package.json`. This is a work in progress to get feedback.

I just saw there was an ongoing similar attempt here https://github.com/depcheck/depcheck/pull/408, I have to check what is the overlap.

### CODE REVIEW

**Comment by rumpl** [comment]
Seems like we have 3 PRs up now for this particular feature, will have to take a really close look at all of those :)

Thanks

**Comment by znarf** [comment]
I've now checked https://github.com/depcheck/depcheck/pull/408 and it's great! It's already supporting configuration in `package.json` out of the box. Also, I was afraid that `yaml` would be mandatory but JSON is also supported, nice.

For parsers, I do prefer the syntax I was proposing here, it's more semantic and closer to the internal API. In the other PR it's:

```json
  "parsers": [
    "*.js:jsx",
    "*.jsx:jsx",
    "*.ts:typescript",
    "*.tsx:typescript"
  ],
```

While I was proposing the following, no string manipulation required:

```json
    "parsers": {
      "*.js": "jsx",
      "*.jsx": "jsx",
      "*.ts": "typescript",
      "*.tsx": "typescript"
    },
```

Other small difference, the other PR is using `ignore` (closer to the CLI) while I was proposing `ignoreMatches` (closer to the API).

**Comment by rumpl** [comment]
@znarf both of those things would be great to have in the other PR, I'll link your comment there

**Comment by Urik** [comment]
@rumpl @znarf I agree that's a good change, we should move `getParsers` from cli.js into the CLI configuration reader.
I'll have that done tomorrow.

**Comment by znarf** [comment]
@Urik fine by me. Looking forward having your great PR ready and merged!

**Pull request closed without merging**
