### PR TITLE
added gatsby special

### PR DESCRIPTION
**Pull request by KaboomFox**

### CODE REVIEW

**Comment by rumpl** [comment]
Thanks soo much for tgis PR!

What does *under review* mean? Should I take a look asap or is there still some stuff to do?

Quick question: depcheck needs motivated people to keep it living and I don’t have always the time, how would you like to be in the core team? It basically only means that you can do releases but still... :)

**Comment by KaboomFox** [comment]
@rumpl Thanks so much! I was having a co-worker review as well.

I'd love to be on the core team. This is a fun project!

**Comment by KaboomFox** [comment]
Any updates on this one?

**Comment by rumpl** [comment]
Merged, sorry for the delay. 

Thanks!

**Comment by rumpl** [comment]
Damn, once again I merge to quickly, @KaboomFox could you please make a new PR that updates the README (add gatsby onto the specials list). Thanks

**Comment by KaboomFox** [comment]
Hey Djordje,

What does the release process look like?

I'd love to release a new version but wanted to know what steps you all
take.

Thanks,
Louise

**Comment by rumpl** [comment]
Hey,

Releasing is as easy as creating a new git tag and pushing it!

Once a tag is pushed, the tests are played and if everything goes well a new release is created on the [releases page in github](https://github.com/depcheck/depcheck/releases) and on npmjs.org.

Wanna release? :)

**Comment by KaboomFox** [comment]
yeah I do! I’ll make a pull request first to update the docs about gatsby.

Thanks,

Louise

**Comment by KaboomFox** [comment]
Hey Djordje,

I ran into an error pushing the tag:  louisef  C02WJ075HTD8  ~  repos 
opensource  depcheck  master  $  git push origin 0.7.3
remote: Permission to depcheck/depcheck.git denied to KaboomFox.
fatal: unable to access 'https://github.com/depcheck/depcheck.git/': The
requested URL returned error: 403

Looks like I don't have permission to push to depcheck.

-Louise

**Comment by rumpl** [comment]
Hey,

There is something weird going on with [your commits](https://github.com/depcheck/depcheck/pull/328/commits), it looks like your git is not configured correctly...

Aslo, could you activate 2FA please?

**Comment by rumpl** [comment]
@KaboomFox all good? Contact me if you need help. Or if you want, I can do a release now and you'll do the next.

**Comment by KaboomFox** [comment]
I still cannot release. I'll email your personal email and we can work it
out.  You can release this time.

Thanks,
Louise

**Pull request merged**
