### PR TITLE
Recognize parser used by feross/standard linter.

### LINKED ISSUE #110: Support feross/standard custom parser
Related: 

- https://github.com/dylang/npm-check/issues/88#issuecomment-196673374
- https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support

/cc @LinusU

### PR DESCRIPTION
**Pull request by lijunle**
Resolve #110

### CODE REVIEW

**Comment by LinusU** [comment]
Awesome work :raised_hands: thank you

**Comment by LinusU** [comment]
Just tried this out but I realise that you haven't cut a new version yet. Would really appreciate it if you published a new version on npm :)

**Comment by lijunle** [comment]
I am implementing the parser for SASS. I want to push to 0.6.1 too.

Besides, ship a new version for depcheck is not enough, npm-check is consuming 0.5.x. Its `package.json` needs to update.

**Comment by LinusU** [comment]
Hmm, that's unfortunate... Looking forward to the next release though :rocket:

**Comment by lijunle** [comment]
@LinusU depcheck@0.6.1 is out, wait for merge of https://github.com/dylang/npm-check/pull/93 and npm-check publish a new version.

**Comment by LinusU** [comment]
Thank you :+1:

**Pull request merged**
