### PR TITLE
support babel.config.js

### PR DESCRIPTION
**Pull request by dword-design**
In Babel 7 it is common practice to have a project-wide babel.config.js, so we should support it

### CODE REVIEW

**Comment by rumpl** [comment]
Thanks for the PR, could you fix the linter erros so that we can merge?

**Comment by dword-design** [comment]
Sorry missed that. Here you go

**Comment by jrnail23** [comment]
In order to properly handle Babel 7, this PR also needs to address babel's plugin and preset renaming (i.e., `babel-plugin-something` is now `@babel/plugin-something`).
see: https://babeljs.io/docs/en/v7-migration#scoped-packages

**Comment by dword-design** [comment]
@jrnail23 hm I don't know exactly what you mean. The scoped packages should be put into babel.config.js, but this shouldn't be related to parsing.

**Comment by rumpl** [comment]
Thanks @dword-design

**Pull request merged**
