### PR TITLE
fix: arguments to @babel/parser

### PR DESCRIPTION
**Pull request by hedgepigdaniel**
Fixes https://github.com/depcheck/depcheck/issues/688

### CODE REVIEW

**Comment by rumpl** [comment]
Thanks for the PR, if this fixes I will need some time to take a look and understand why this suddenly stopped working, [there is this other issue](https://github.com/depcheck/depcheck/issues/687) saying that an update to `@babel/parser` made things break for us. But I'm not sure I understand why we pick that updated babel parser, we are publishing a bundled package...

**Comment by m4eryk** [comment]
@hedgepigdaniel can you update OR? it's so important

**Comment by znarf** [comment]
@rumpl depcheck doesn't bundle a fixed dependency as it's using a loose version `"@babel/parser": "^7.12.5",` in package.json. If there is suitable version that matches, it will use it. That's valid for `@babel/parser@7.16.7`.

The breaking change in babel can be seen here: https://github.com/babel/babel/commit/f4236f43a119da17904c466e5d9c375141cb12a7

Seems the syntax in typescript.js was wrong but simply ignored before 7.16.7. It started to break after this.

Since the syntax was already correct in es7.js, jsx.js and vue.js, I think the change is safe.

**Comment by znarf** [comment]
The change looks good but ultimately closing as there is a duplicate PR here #692

**Pull request closed without merging**
