### PR TITLE
feat: add --quiet flag to suppress No depcheck issue messages

### LINKED ISSUE #759: Flag to make logs readable and less verbose
Description:
Reading the logs generated by dep check is very time-consuming, I am personally not interested in seeing hundreds of lines of  `YN0000: [@package]: No depcheck issue` to find an unused dependency.
Removing the verbose flag doesn't help either since it wouldn't display the dependency that actually has an issue and will still log hundreds of lines of `No depcheck issue`.

it would be more useful to remove the log for  `No depcheck issue` all together  when removing the `--verbose` flag.

My project is huge and this would really help.

### PR DESCRIPTION
**Pull request by openam**
Closes #759

### CODE REVIEW

**Comment by rumpl** [comment]
In my mind a `--quiet` would make depcheck not print anything at all, could we update it so that `--quiet` doesn't print anything?

**Comment by openam** [comment]
@rumpl That sounds more like a `--silent` tag. The point of this PR was to make it so that people using a monorepo wouldn't have to look through 100 lines of `No depcheck issue` noise to find the one line that has an error. e.g.

```
many more
...
constants: No depcheck issue
permissions: No depcheck issue
utils: No depcheck issue
errors: No depcheck issue
logger: No depcheck issue
aws-sqs: No depcheck issue
aws-s3: No depcheck issue
koa-logger: No depcheck issue
opsgenie: No depcheck issue
config: Missing dependencies
config: * logger: ./index.js
geo: No depcheck issue
proxy: No depcheck issue
ably: No depcheck issue
dashboard: No depcheck issue
authenticator: No depcheck issue
...
plus many more
...
lerna ERR! Received non-zero exit code 255 during execution
lerna success exec Executed command in 108 packages: "depcheck"
```

vs

```
config: Missing dependencies
config: * logger: ./index.js
lerna ERR! Received non-zero exit code 255 during execution
lerna success exec Executed command in 108 packages: "depcheck --quiet"
```

**Comment by seansfkelley** [comment]
Throwing my hat in the ring here as a commenter on the original issue: I agree on the distinction between `--quiet` and `--silent` (though can't really imagine when I would want to use the latter with a tool like depcheck). When I give `--quiet` to some arbitrary tool, I typically expect only "essential" output to be printed (or: output requiring an action from me). Maybe there is more non-essential logging that should be covered by `--quiet` than just this line, but I definitely _do_ want to see in which file the issues were found.

**Review by rumpl — APPROVED** [review]

**Comment by openam** [comment]
@rumpl Is there anything I need to do to get a version released that contains this change? Unfortunately this was merged in like 3 days after the last release.

**Comment by rumpl** [comment]
You only need to ask, I'll make a new release tomorrow ;)

**Comment by openam** [comment]
@rumpl would you please make a release with this `--quiet` flag.

**Comment by rumpl** [comment]
@openam Version 1.4.6 with this option was just released!

**Pull request merged**
