### PR TITLE
feat(sass parser): support @use and namespace syntax

### LINKED ISSUE #576: Sass 'use' syntax not working
Hi,
Thanks for this useful library.
I have an issue with SASS `use` syntax not working for me.
In my `scss` files -> `@use '@myNS/styles/styles.scss';`
When running `depCheck` it says that `@myNS/styles` is an unused package in my project.

### PR DESCRIPTION
**Pull request by YonatanKra**
While working with SASS only modules, I found out the depcheck did not work correctly.
I've added some use cases that didn't work (like `@use` or using `@use '@namespace/libname'` syntax.

Closes #576

### CODE REVIEW

**Comment by rumpl** [comment]
@YonatanKra thanks for this PR, the tests seem to fail on node-12 on windows, could you investigate?

**Comment by YonatanKra** [comment]
> @YonatanKra thanks for this PR, the tests seem to fail on node-12 on windows, could you investigate?

As far as I can see it is a linting issue on windows for files that were not touched by me. Can u tell why?

**Comment by rumpl** [comment]
> > @YonatanKra thanks for this PR, the tests seem to fail on node-12 on windows, could you investigate?
> 
> As far as I can see it is a linting issue on windows for files that were not touched by me. Can u tell why?

The linting errors were there before, they are not real error (I have no idea why we have these), the real errors are:
```

  2) depcheck
       should support SASS/SCSS syntax:

      AssertionError: expected Array [ 'sass-dep', 'unused-sass-dep' ] to equal Array [ 'unused-sass-dep' ] (at length, A has 2 and B has 1)
      + expected - actual

       [
      -  "sass-dep"
         "unused-sass-dep"
       ]
      
      at Assertion.fail (node_modules\should\cjs\should.js:275:17)
      at Assertion.eql (node_modules\should\cjs\should.js:356:19)
      at D:\a\depcheck\depcheck\test\/index.js:33:36
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by rumpl** [comment]
You need to scroll really far and if you squint enough you will see the failing tests :)

**Comment by YonatanKra** [comment]
> You need to scroll really far and if you squint enough you will see the failing tests :)

I scrolled - but forgot not to blink ;)
The linting errors are so dominant...

Anyway, the fact it works on Mac and not on Windows was a big hint.

**Comment by rumpl** [comment]
> I scrolled - but forgot not to blink ;)

😂

Sorry about that

**Comment by rumpl** [comment]
Thanks!

**Pull request merged**
