### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by VincentLanglet**
I made some try to find the rules already use for this project:
- singleQuote over doubleQuote
- arrowParens always
- trailingComma

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@rumpl Funny,

I got
```
Unused devDependencies
* eslint-config-prettier
```
But i use it, see https://github.com/prettier/eslint-plugin-prettier#recommended-configuration

`plugin:prettier/recommended` is enough.

**Comment by rumpl** [comment]
Damn... I guess we will need a special case for this prettier plugin...

**Comment by rumpl** [comment]
Just opened a PR #464

**Comment by rumpl** [comment]
Awesome thanks @VincentLanglet

**Pull request merged**
