### PR TITLE
Add index.d.ts

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by rumpl** [comment]
@sveyret regarding your email look at this :)

**Comment by sveyret** [comment]
It looks like this does not have the latest modifications posted by @rumpl to DefinitlyTyped.

**Comment by VincentLanglet** [comment]
Indeed, I found the PR and update the index.d.ts file

**Comment by rumpl** [comment]
Definitely typed has a test for the d.ts file, could we add it too?

**Comment by VincentLanglet** [comment]
I don't remember packages with test for the `d.ts` file, except DefinitivelyTyped.

If you want to add test for this file, you need something to run theses tests.
I can't help about this.

**Comment by rumpl** [comment]
It's ok for now

**Pull request merged**
