### PR TITLE
Add support for TSLint

### PR DESCRIPTION
**Pull request by LinusU**
The diff is a bit hard to read, here is a diff between the previous `src/special/eslint.js` and the new `src/util/linters.js`:

```diff
--- src/special/eslint.js	2018-08-09 14:54:33.000000000 +0100
+++ src/utils/linters.js	2018-08-09 14:44:03.000000000 +0100
@@ -37,51 +37,51 @@
   return [obj];
 }
 
-function isEslintConfigAnAbsolutePath(specifier) {
+function isLinterConfigAnAbsolutePath(specifier) {
   return path.isAbsolute(specifier);
 }
 
-function isEslintConfigARelativePath(specifier) {
+function isLinterConfigARelativePath(specifier) {
   return lodash.startsWith(specifier, './') || lodash.startsWith(specifier, '../');
 }
 
-function isEslintConfigFromAPlugin(specifier) {
+function isLinterConfigFromAPlugin(specifier) {
   return lodash.startsWith(specifier, 'plugin:');
 }
 
-function isEslintConfigFromAScopedModule(specifier) {
+function isLinterConfigFromAScopedModule(specifier) {
   return lodash.startsWith(specifier, '@');
 }
 
-function isEslintConfigFromAFullyQualifiedModuleName(specifier, prefix) {
+function isLinterConfigFromAFullyQualifiedModuleName(specifier, prefix) {
   return lodash.startsWith(specifier, prefix);
 }
 
-function resolvePresetPackage(preset, rootDir) {
+function resolvePresetPackage(flavour, preset, rootDir) {
   // inspired from https://github.com/eslint/eslint/blob/5b4a94e26d0ef247fe222dacab5749805d9780dd/lib/config/config-file.js#L347
-  if (isEslintConfigAnAbsolutePath(preset)) {
+  if (isLinterConfigAnAbsolutePath(preset)) {
     return preset;
   }
-  if (isEslintConfigARelativePath(preset)) {
+  if (isLinterConfigARelativePath(preset)) {
     return path.resolve(rootDir, preset);
   }
 
   const { prefix, specifier } = (
-    isEslintConfigFromAPlugin(preset)
-    ? { prefix: 'eslint-plugin-', specifier: preset.substring(preset.indexOf(':') + 1) }
-    : { prefix: 'eslint-config-', specifier: preset }
+    isLinterConfigFromAPlugin(preset)
+    ? { prefix: `${flavour}-plugin-`, specifier: preset.substring(preset.indexOf(':') + 1) }
+    : { prefix: `${flavour}-config-`, specifier: preset }
   );
 
-  if (isEslintConfigFromAScopedModule(specifier)) {
+  if (isLinterConfigFromAScopedModule(specifier)) {
     const scope = specifier.substring(0, specifier.indexOf('/'));
     const module = specifier.substring(specifier.indexOf('/') + 1);
 
-    if (isEslintConfigFromAFullyQualifiedModuleName(module, prefix)) {
+    if (isLinterConfigFromAFullyQualifiedModuleName(module, prefix)) {
       return specifier;
     }
     return `${scope}/${prefix}${module}`;
   }
-  if (isEslintConfigFromAFullyQualifiedModuleName(specifier, prefix)) {
+  if (isLinterConfigFromAFullyQualifiedModuleName(specifier, prefix)) {
     return specifier;
   }
   return `${prefix}${specifier}`;
@@ -99,13 +99,13 @@
   }
 }
 
-function checkConfig(config, rootDir) {
+function checkConfig(flavour, config, rootDir) {
   const parser = wrapToArray(config.parser);
-  const plugins = wrapToArray(config.plugins).map(plugin => `eslint-plugin-${plugin}`);
+  const plugins = wrapToArray(config.plugins).map(plugin => `${flavour}-plugin-${plugin}`);
 
   const presets = wrapToArray(config.extends)
-    .filter(preset => preset !== 'eslint:recommended')
-    .map(preset => resolvePresetPackage(preset, rootDir));
+    .filter(preset => preset !== `${flavour}:recommended`)
+    .map(preset => resolvePresetPackage(flavour, preset, rootDir));
 
   const presetPackages = presets
     .filter(preset => !path.isAbsolute(preset))
@@ -113,18 +113,19 @@
 
   const presetDeps = lodash(presets)
     .map(preset => loadConfig(preset, rootDir))
-    .map(presetConfig => checkConfig(presetConfig, rootDir))
+    .map(presetConfig => checkConfig(flavour, presetConfig, rootDir))
     .flatten()
     .value();
 
   return lodash.union(parser, plugins, presetPackages, presetDeps);
 }
 
-export default function parseESLint(content, filename, deps, rootDir) {
+export default function parseLinter(flavour, content, filename, deps, rootDir) {
   const basename = path.basename(filename);
-  if (/^\.eslintrc(\.json|\.js|\.yml|\.yaml)?$/.test(basename)) {
+  const filenameRegex = new RegExp(`^\\.${flavour}rc(\\.json|\\.js|\\.yml|\\.yaml)?$`);
+  if (filenameRegex.test(basename)) {
     const config = parse(content);
-    return checkConfig(config, rootDir);
+    return checkConfig(flavour, config, rootDir);
   }
 
   return [];
```

### CODE REVIEW

**Comment by rumpl** [comment]
Could you update the README too please?

**Comment by LinusU** [comment]
Of course, forgot about that ☺️

**Comment by LinusU** [comment]
> about sharing this logic for eslint as well -- did you want to do that in this PR as well, or save it for another time?

I did do that here ☺️ 

> Since you've just spent some time looking at the linter code, perhaps it's worth giving a look to #193, #234, and #244?

I'll take a look at them and land them manually 👍

**Comment by mnkhouri** [comment]
> I did do that here ☺️

@LinusU perhaps I'm misunderstanding -- after this PR, I would expect `/src/special/eslint.js` to look like this:

``` 
import parseLinter from '../utils/linters';

export default function parseTSLint(content, filename, deps, rootDir) {
  return parseLinter('eslint', content, filename, deps, rootDir);
}
```

However, instead, `/src/special/eslint.js` has its own copy of all the logic? https://github.com/depcheck/depcheck/blob/master/src/special/eslint.js

**Comment by LinusU** [comment]
Ah shit 🤦‍♂️ 🤦‍♂️ 

I ran `git checkout -- src/special/eslint.js` in order to generate the diff I posted in the pull request, but then when I amended the commit to include the readme I accidentally committed that as well 🤦‍♂️ 

New pull request incoming!

**Comment by LinusU** [comment]
here we go: https://github.com/depcheck/depcheck/pull/270

**Pull request merged**
