### PR TITLE
Support Vue.js (closes #195)

### LINKED ISSUE #195: Support Vue.js
Hello, thanks for the project!

I would really like to see a `vue.js` special plugin, so we could use it with `.vue` files.

Any plans on it?

### PR DESCRIPTION
**Pull request by oligot**
By using the module [vue-template-compiler](https://www.npmjs.com/package/vue-template-compiler) to parse and extract the script part from .vue files

Also added a basic test case for .vue files

### CODE REVIEW

**Comment by westy92** [comment]
Add Vue to the README.

**Comment by oligot** [comment]
done

**Comment by LinusU** [comment]
Landing this would help us solve https://github.com/dylang/npm-check/issues/290 ☺️

**Comment by lijunle** [comment]
Hi, @LinusU  Are you willing to help on maintaining this project? I am busy on the company works. It could be great that you could help!

**Comment by mnkhouri** [comment]
Thanks @oligot ! I'll get a release out within a week, as I'm working through a few other open PRs/issues

**Comment by oligot** [comment]
Ok, great !

**Comment by LinusU** [comment]
@lijunle @mnkhouri I'm still interested in helping to maintain if you guys want help :)

Using this in npm-check which I'm also a maintainer of 🙌 

I'm `linusu` on npm

**Comment by lijunle** [comment]
@LinusU I am sorry that, I suppose to add you to the team but forget the write permission. Does it work now?

**Comment by LinusU** [comment]
Yes, thanks ❤️

**Pull request merged**
